// Mocks generated by Mockito 5.4.6 from annotations
// in lispinto_chat/test/widgets/message_bubble_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lispinto_chat/services/link_image_detector.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LinkImageDetector].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinkImageDetector extends _i1.Mock implements _i2.LinkImageDetector {
  MockLinkImageDetector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ImageType?> isImage(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#isImage, [url]),
            returnValue: _i3.Future<_i2.ImageType?>.value(),
          )
          as _i3.Future<_i2.ImageType?>);

  @override
  bool isKnown(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#isKnown, [url]),
            returnValue: false,
          )
          as bool);

  @override
  _i2.ImageType? getCachedStatus(String? url) =>
      (super.noSuchMethod(Invocation.method(#getCachedStatus, [url]))
          as _i2.ImageType?);
}
