// Mocks generated by Mockito 5.4.6 from annotations
// in lispinto_chat/test/widgets/text_styling_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lispinto_chat/models/link_metadata.dart' as _i4;
import 'package:lispinto_chat/services/link_preview_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LinkPreviewService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinkPreviewService extends _i1.Mock
    implements _i2.LinkPreviewService {
  MockLinkPreviewService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.LinkPreviewInfo?> fetchInfo(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#fetchInfo, [url]),
            returnValue: _i3.Future<_i2.LinkPreviewInfo?>.value(),
          )
          as _i3.Future<_i2.LinkPreviewInfo?>);

  @override
  _i2.LinkPreviewInfo? getCachedInfo(String? url) =>
      (super.noSuchMethod(Invocation.method(#getCachedInfo, [url]))
          as _i2.LinkPreviewInfo?);

  @override
  _i3.Future<_i4.LinkMetadata?> fetchMetadata(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMetadata, [url]),
            returnValue: _i3.Future<_i4.LinkMetadata?>.value(),
          )
          as _i3.Future<_i4.LinkMetadata?>);
}
